[deps]
H5Zblosc = "c8ec2601-a99c-407f-b158-e79c03c2f5f7"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
OpenMPI_jll = "fe0851c0-eecd-5654-98d4-656369965a5c"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqAdamsBashforthMoulton = "89bda076-bce5-4f1c-845f-551c83cdda9a"
PMFRG = "37d616f8-0bcb-4e18-9a76-f5d18f52650d"
PencilArrays = "0e08944d-e94e-41b1-9406-dcf66b6a9d2e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpinFRGLattices = "053fb7f8-31b7-4f68-aef8-4452b415dd8c"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
