[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PMFRG = "37d616f8-0bcb-4e18-9a76-f5d18f52650d"
PencilArrays = "0e08944d-e94e-41b1-9406-dcf66b6a9d2e"
SpinFRGLattices = "053fb7f8-31b7-4f68-aef8-4452b415dd8c"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
